"""
This type stub file was generated by pyright.
"""

import sys
from tqdm import tqdm
from tqdm.auto import tqdm as tqdm_auto
from tqdm.utils import ObjectWrapper
from functools import wraps

"""
Thin wrappers around common functions.

Subpackages contain potentially unstable extensions.
"""
__author__ = { "github.com/": ["casperdcl"] }
class DummyTqdmFile(ObjectWrapper):
    """Dummy file-like that will write to tqdm"""
    def write(self, x, nolock=...):
        ...
    


def builtin_iterable(func):
    """Wraps `func()` output in a `list()` in py2"""
    ...

def tenumerate(iterable, start=..., total=..., tqdm_class=..., **tqdm_kwargs):
    """
    Equivalent of `numpy.ndenumerate` or builtin `enumerate`.

    Parameters
    ----------
    tqdm_class  : [default: tqdm.auto.tqdm].
    """
    ...

@builtin_iterable
def tzip(iter1, *iter2plus, **tqdm_kwargs):
    """
    Equivalent of builtin `zip`.

    Parameters
    ----------
    tqdm_class  : [default: tqdm.auto.tqdm].
    """
    ...

@builtin_iterable
def tmap(function, *sequences, **tqdm_kwargs):
    """
    Equivalent of builtin `map`.

    Parameters
    ----------
    tqdm_class  : [default: tqdm.auto.tqdm].
    """
    ...

