MOCK_API = {
    # healthcheck
    "https://api.census.gov/data/2019/acs/acs1.json": "OK",
    # groups
    "https://api.census.gov/data/2019/acs/acs1/groups.json": {
        "groups": [
            {
                "name": "B17015",
                "description": "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY FAMILY TYPE BY SOCIAL SECURITY INCOME BY SUPPLEMENTAL SECURITY INCOME (SSI) AND CASH PUBLIC ASSISTANCE INCOME",
                "variables": "https://api.census.gov/data/2019/acs/acs1/groups/B17015.json",
            },
            {
                "name": "B18104",
                "description": "SEX BY AGE BY COGNITIVE DIFFICULTY",
                "variables": "https://api.census.gov/data/2019/acs/acs1/groups/B18104.json",
            },
            {
                "name": "B18105",
                "description": "SEX BY AGE BY AMBULATORY DIFFICULTY",
                "variables": "https://api.census.gov/data/2019/acs/acs1/groups/B18105.json",
            },
        ]
    },
    # all variables
    "https://api.census.gov/data/2019/acs/acs1/variables.json": {
        "variables": {
            "B17015_001E": {
                "label": "Estimate!!Total:",
                "concept": "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY FAMILY TYPE BY SOCIAL SECURITY INCOME BY SUPPLEMENTAL SECURITY INCOME (SSI) AND CASH PUBLIC ASSISTANCE INCOME",
                "predicateType": "int",
                "group": "B17015",
                "limit": 0,
                "predicateOnly": True,
            },
            "B17015_001M": {
                "label": "Margin of Error!!Total:",
                "concept": "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY FAMILY TYPE BY SOCIAL SECURITY INCOME BY SUPPLEMENTAL SECURITY INCOME (SSI) AND CASH PUBLIC ASSISTANCE INCOME",
                "predicateType": "int",
                "group": "B17015",
                "limit": 0,
                "predicateOnly": True,
            },
            "B17015_001MA": {
                "label": "Annotation of Margin of Error!!Total:",
                "concept": "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY FAMILY TYPE BY SOCIAL SECURITY INCOME BY SUPPLEMENTAL SECURITY INCOME (SSI) AND CASH PUBLIC ASSISTANCE INCOME",
                "predicateType": "string",
                "group": "B17015",
                "limit": 0,
                "predicateOnly": True,
            },
            "B17015_001EA": {
                "label": "Annotation of Estimate!!Total:",
                "concept": "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY FAMILY TYPE BY SOCIAL SECURITY INCOME BY SUPPLEMENTAL SECURITY INCOME (SSI) AND CASH PUBLIC ASSISTANCE INCOME",
                "predicateType": "string",
                "group": "B17015",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18104_001MA": {
                "label": "Annotation of Margin of Error!!Total:",
                "concept": "SEX BY AGE BY COGNITIVE DIFFICULTY",
                "predicateType": "string",
                "group": "B18104",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18104_001EA": {
                "label": "Annotation of Estimate!!Total:",
                "concept": "SEX BY AGE BY COGNITIVE DIFFICULTY",
                "predicateType": "string",
                "group": "B18104",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18104_001M": {
                "label": "Margin of Error!!Total:",
                "concept": "SEX BY AGE BY COGNITIVE DIFFICULTY",
                "predicateType": "int",
                "group": "B18104",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18104_001E": {
                "label": "Estimate!!Total:",
                "concept": "SEX BY AGE BY COGNITIVE DIFFICULTY",
                "predicateType": "int",
                "group": "B18104",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18105_001MA": {
                "label": "Annotation of Margin of Error!!Total:",
                "concept": "SEX BY AGE BY AMBULATORY DIFFICULTY",
                "predicateType": "string",
                "group": "B18105",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18105_001EA": {
                "label": "Annotation of Estimate!!Total:",
                "concept": "SEX BY AGE BY AMBULATORY DIFFICULTY",
                "predicateType": "string",
                "group": "B18105",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18105_001E": {
                "label": "Estimate!!Total:",
                "concept": "SEX BY AGE BY AMBULATORY DIFFICULTY",
                "predicateType": "int",
                "group": "B18105",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18105_001M": {
                "label": "Margin of Error!!Total:",
                "concept": "SEX BY AGE BY AMBULATORY DIFFICULTY",
                "predicateType": "int",
                "group": "B18105",
                "limit": 0,
                "predicateOnly": True,
            },
        }
    },
    #############################
    ##### grouped variables #####
    #############################
    "https://api.census.gov/data/2019/acs/acs1/groups/B17015.json": {
        "variables": {
            "B17015_001E": {
                "label": "Estimate!!Total:",
                "concept": "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY FAMILY TYPE BY SOCIAL SECURITY INCOME BY SUPPLEMENTAL SECURITY INCOME (SSI) AND CASH PUBLIC ASSISTANCE INCOME",
                "predicateType": "int",
                "group": "B17015",
                "limit": 0,
                "predicateOnly": True,
            },
            "B17015_001M": {
                "label": "Margin of Error!!Total:",
                "concept": "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY FAMILY TYPE BY SOCIAL SECURITY INCOME BY SUPPLEMENTAL SECURITY INCOME (SSI) AND CASH PUBLIC ASSISTANCE INCOME",
                "predicateType": "int",
                "group": "B17015",
                "limit": 0,
                "predicateOnly": True,
            },
            "B17015_001MA": {
                "label": "Annotation of Margin of Error!!Total:",
                "concept": "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY FAMILY TYPE BY SOCIAL SECURITY INCOME BY SUPPLEMENTAL SECURITY INCOME (SSI) AND CASH PUBLIC ASSISTANCE INCOME",
                "predicateType": "string",
                "group": "B17015",
                "limit": 0,
                "predicateOnly": True,
            },
            "B17015_001EA": {
                "label": "Annotation of Estimate!!Total:",
                "concept": "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY FAMILY TYPE BY SOCIAL SECURITY INCOME BY SUPPLEMENTAL SECURITY INCOME (SSI) AND CASH PUBLIC ASSISTANCE INCOME",
                "predicateType": "string",
                "group": "B17015",
                "limit": 0,
                "predicateOnly": True,
            },
        }
    },
    "https://api.census.gov/data/2019/acs/acs1/groups/B18104.json": {
        "variables": {
            "B18104_001MA": {
                "label": "Annotation of Margin of Error!!Total:",
                "concept": "SEX BY AGE BY COGNITIVE DIFFICULTY",
                "predicateType": "string",
                "group": "B18104",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18104_001EA": {
                "label": "Annotation of Estimate!!Total:",
                "concept": "SEX BY AGE BY COGNITIVE DIFFICULTY",
                "predicateType": "string",
                "group": "B18104",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18104_001M": {
                "label": "Margin of Error!!Total:",
                "concept": "SEX BY AGE BY COGNITIVE DIFFICULTY",
                "predicateType": "int",
                "group": "B18104",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18104_001E": {
                "label": "Estimate!!Total:",
                "concept": "SEX BY AGE BY COGNITIVE DIFFICULTY",
                "predicateType": "int",
                "group": "B18104",
                "limit": 0,
                "predicateOnly": True,
            },
        }
    },
    "https://api.census.gov/data/2019/acs/acs1/groups/B18105.json": {
        "variables": {
            "B18105_001MA": {
                "label": "Annotation of Margin of Error!!Total:",
                "concept": "SEX BY AGE BY AMBULATORY DIFFICULTY",
                "predicateType": "string",
                "group": "B18105",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18105_001EA": {
                "label": "Annotation of Estimate!!Total:",
                "concept": "SEX BY AGE BY AMBULATORY DIFFICULTY",
                "predicateType": "string",
                "group": "B18105",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18105_001E": {
                "label": "Estimate!!Total:",
                "concept": "SEX BY AGE BY AMBULATORY DIFFICULTY",
                "predicateType": "int",
                "group": "B18105",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18105_001M": {
                "label": "Margin of Error!!Total:",
                "concept": "SEX BY AGE BY AMBULATORY DIFFICULTY",
                "predicateType": "int",
                "group": "B18105",
                "limit": 0,
                "predicateOnly": True,
            },
        }
    },
    # stats
    "https://api.census.gov/data/2019/acs/acs1?get=NAME,B17015_001E,B18104_001E,B18105_001E&for=congressional%20district:*&in=state:01": [
        [
            "NAME",
            "B17015_001E",
            "B18104_001E",
            "B18105_001E",
            "state",
            "congressional district",
        ],
        [
            "Congressional District 1 (116th Congress), Alabama",
            "172441",
            "664816",
            "664816",
            "01",
            "01",
        ],
        [
            "Congressional District 3 (116th Congress), Alabama",
            "184320",
            "664930",
            "664930",
            "01",
            "03",
        ],
        [
            "Congressional District 5 (116th Congress), Alabama",
            "195668",
            "681411",
            "681411",
            "01",
            "05",
        ],
        [
            "Congressional District 4 (116th Congress), Alabama",
            "179508",
            "640347",
            "640347",
            "01",
            "04",
        ],
        [
            "Congressional District 7 (116th Congress), Alabama",
            "151225",
            "620542",
            "620542",
            "01",
            "07",
        ],
        [
            "Congressional District 2 (116th Congress), Alabama",
            "168129",
            "610312",
            "610312",
            "01",
            "02",
        ],
        [
            "Congressional District 6 (116th Congress), Alabama",
            "186592",
            "653559",
            "653559",
            "01",
            "06",
        ],
    ],
    # stats -- batched
    "https://api.census.gov/data/2019/acs/acs1?get=NAME,B17015_001E&for=congressional%20district:*&in=state:01": [
        [
            "NAME",
            "B17015_001E",
            "state",
            "congressional district",
        ],
        [
            "Congressional District 1 (116th Congress), Alabama",
            "172441",
            "01",
            "01",
        ],
        [
            "Congressional District 3 (116th Congress), Alabama",
            "184320",
            "01",
            "03",
        ],
        [
            "Congressional District 5 (116th Congress), Alabama",
            "195668",
            "01",
            "05",
        ],
        [
            "Congressional District 4 (116th Congress), Alabama",
            "179508",
            "01",
            "04",
        ],
        [
            "Congressional District 7 (116th Congress), Alabama",
            "151225",
            "01",
            "07",
        ],
        [
            "Congressional District 2 (116th Congress), Alabama",
            "168129",
            "01",
            "02",
        ],
        [
            "Congressional District 6 (116th Congress), Alabama",
            "186592",
            "01",
            "06",
        ],
    ],
    "https://api.census.gov/data/2019/acs/acs1?get=NAME,B18104_001E&for=congressional%20district:*&in=state:01": [
        [
            "NAME",
            "B18104_001E",
            "state",
            "congressional district",
        ],
        [
            "Congressional District 1 (116th Congress), Alabama",
            "664816",
            "01",
            "01",
        ],
        [
            "Congressional District 3 (116th Congress), Alabama",
            "664930",
            "01",
            "03",
        ],
        [
            "Congressional District 5 (116th Congress), Alabama",
            "681411",
            "01",
            "05",
        ],
        [
            "Congressional District 4 (116th Congress), Alabama",
            "640347",
            "01",
            "04",
        ],
        [
            "Congressional District 7 (116th Congress), Alabama",
            "620542",
            "01",
            "07",
        ],
        [
            "Congressional District 2 (116th Congress), Alabama",
            "610312",
            "01",
            "02",
        ],
        [
            "Congressional District 6 (116th Congress), Alabama",
            "653559",
            "01",
            "06",
        ],
    ],
    "https://api.census.gov/data/2019/acs/acs1?get=NAME,B18105_001E&for=congressional%20district:*&in=state:01": [
        [
            "NAME",
            "B18105_001E",
            "state",
            "congressional district",
        ],
        [
            "Congressional District 1 (116th Congress), Alabama",
            "664816",
            "01",
            "01",
        ],
        [
            "Congressional District 3 (116th Congress), Alabama",
            "664930",
            "01",
            "03",
        ],
        [
            "Congressional District 5 (116th Congress), Alabama",
            "681411",
            "01",
            "05",
        ],
        [
            "Congressional District 4 (116th Congress), Alabama",
            "640347",
            "01",
            "04",
        ],
        [
            "Congressional District 7 (116th Congress), Alabama",
            "620542",
            "01",
            "07",
        ],
        [
            "Congressional District 2 (116th Congress), Alabama",
            "610312",
            "01",
            "02",
        ],
        [
            "Congressional District 6 (116th Congress), Alabama",
            "653559",
            "01",
            "06",
        ],
    ],
    # supported geographies
    "https://api.census.gov/data/2019/acs/acs1/geography.json": {
        "default": [{"isDefault": "True"}],
        "fips": [
            {"name": "us", "geoLevelDisplay": "010", "referenceDate": "2019-01-01"},
            {"name": "region", "geoLevelDisplay": "020", "referenceDate": "2019-01-01"},
            {
                "name": "division",
                "geoLevelDisplay": "030",
                "referenceDate": "2019-01-01",
            },
            {"name": "state", "geoLevelDisplay": "040", "referenceDate": "2019-01-01"},
            {
                "name": "county",
                "geoLevelDisplay": "050",
                "referenceDate": "2019-01-01",
                "requires": ["state"],
                "wildcard": ["state"],
                "optionalWithWCFor": "state",
            },
            {
                "name": "congressional district",
                "geoLevelDisplay": "500",
                "referenceDate": "2019-01-01",
                "requires": ["state"],
                "wildcard": ["state"],
                "optionalWithWCFor": "state",
            },
        ],
    },
    # geography codes
    "https://api.census.gov/data/2019/acs/acs1?get=NAME&for=congressional%20district:*&in=state:01": [
        ["NAME", "state", "congressional district"],
        ["Congressional District 1 (116th Congress), Alabama", "01", "01"],
        ["Congressional District 3 (116th Congress), Alabama", "01", "03"],
        ["Congressional District 5 (116th Congress), Alabama", "01", "05"],
        ["Congressional District 4 (116th Congress), Alabama", "01", "04"],
        ["Congressional District 7 (116th Congress), Alabama", "01", "07"],
        ["Congressional District 2 (116th Congress), Alabama", "01", "02"],
        ["Congressional District 6 (116th Congress), Alabama", "01", "06"],
    ],
    # list of censuses
    "https://api.census.gov/data.json": {
        "@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
        "@id": "https://api.census.gov/data/1999/nonemp.json",
        "@type": "dcat:Catalog",
        "conformsTo": "https://project-open-data.cio.gov/v1.1/schema",
        "describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
        "dataset": [
            {
                "c_vintage": 2000,
                "c_dataset": ["dec", "sf4"],
                "c_geographyLink": "https://api.census.gov/data/2000/dec/sf4/geography.json",
                "c_variablesLink": "https://api.census.gov/data/2000/dec/sf4/variables.json",
                "c_tagsLink": "https://api.census.gov/data/2000/dec/sf4/tags.json",
                "c_examplesLink": "https://api.census.gov/data/2000/dec/sf4/examples.json",
                "c_groupsLink": "https://api.census.gov/data/2000/dec/sf4/groups.json",
                "c_valuesLink": "https://api.census.gov/data/2000/dec/sf4/values.json",
                "c_documentationLink": "https://www.census.gov/developer/",
                "c_isAggregate": True,
                "c_isCube": True,
                "c_isAvailable": True,
                "@type": "dcat:Dataset",
                "title": "Decennial Census: Summary File 4",
                "description": "Summary File 4 is repeated or iterated for the total population and 335 additional population groups: 132 race groups,78 American Indian and Alaska Native tribe categories, 39 Hispanic or Latino groups, and 86 ancestry groups.Tables for any population group excluded from SF 2 because the group's total population in a specific geographic area did not meet the SF 2 threshold of 100 people are excluded from SF 4. Tables in SF 4 shown for any of the above population groups will only be shown if there are at least 50 unweighted sample cases in a specific geographic area. The same 50 unweighted sample cases also applied to ancestry iterations. In an iterated file such as SF 4, the universes households, families, and occupied housing units are classified by the race or ethnic group of the householder. The universe subfamilies is classified by the race or ethnic group of the reference person for the subfamily. In a husband/wife subfamily, the reference person is the husband; in a parent/child subfamily, the reference person is always the parent. The universes population in households, population in families, and population in subfamilies are classified by the race or ethnic group of the inidviduals within the household, family, or subfamily without regard to the race or ethnicity of the householder. Notes follow selected tables to make the classification of the universe clear. In any population table where there is no note, the universe classification is always based on the race or ethnicity of the person. In all housing tables, the universe classification is based on the race or ethnicity of the householder.",
                "distribution": [
                    {
                        "@type": "dcat:Distribution",
                        "accessURL": "https://api.census.gov/data/2000/dec/sf4",
                        "description": "API endpoint",
                        "format": "API",
                        "mediaType": "application/json",
                        "title": "API endpoint",
                    }
                ],
                "contactPoint": {
                    "fn": "Census Bureau Call Center",
                    "hasEmail": "mailto:pio@census.gov",
                },
                "identifier": "https://api.census.gov/data/id/DECENNIALSF42000",
                "keyword": [],
                "license": "https://creativecommons.org/publicdomain/zero/1.0/",
                "modified": "2020-02-27 00:00:00.0",
                "programCode": ["006:004"],
                "references": ["https://www.census.gov/developers/"],
                "temporal": "unidentified",
                "publisher": {
                    "@type": "org:Organization",
                    "name": "U.S. Census Bureau",
                    "subOrganizationOf": {
                        "@type": "org:Organization",
                        "name": "U.S. Department Of Commerce",
                        "subOrganizationOf": {
                            "@type": "org:Organization",
                            "name": "U.S. Government",
                        },
                    },
                },
            },
            {
                "c_vintage": 2017,
                "c_dataset": ["ecneoyinv"],
                "c_geographyLink": "https://api.census.gov/data/2017/ecneoyinv/geography.json",
                "c_variablesLink": "https://api.census.gov/data/2017/ecneoyinv/variables.json",
                "c_tagsLink": "https://api.census.gov/data/2017/ecneoyinv/tags.json",
                "c_examplesLink": "https://api.census.gov/data/2017/ecneoyinv/examples.json",
                "c_groupsLink": "https://api.census.gov/data/2017/ecneoyinv/groups.json",
                "c_valuesLink": "https://api.census.gov/data/2017/ecneoyinv/values.json",
                "c_documentationLink": "https://www.census.gov/developer/",
                "c_isAggregate": True,
                "c_isAvailable": True,
                "@type": "dcat:Dataset",
                "title": "Economic Census: Economic Census of the United States: Wholesale Trade: Inventories by Valuation Method for the U.S.",
                "accessLevel": "public",
                "bureauCode": ["006:07"],
                "description": "This dataset presents statistics for Wholesale Trade:  Inventories by Valuation Method for the U.S.",
                "distribution": [
                    {
                        "@type": "dcat:Distribution",
                        "accessURL": "https://api.census.gov/data/2017/ecneoyinv",
                        "description": "API endpoint",
                        "format": "API",
                        "mediaType": "application/json",
                        "title": "API endpoint",
                    }
                ],
                "contactPoint": {
                    "fn": "Data User Outreach",
                    "hasEmail": "mailto:ewd.outreach@census.gov",
                },
                "identifier": "https://api.census.gov/data/id/ECNEOYINV2017",
                "keyword": [],
                "license": "https://creativecommons.org/publicdomain/zero/1.0/",
                "modified": "2020-06-17 00:00:00.0",
                "programCode": ["006:007"],
                "references": ["https://www.census.gov/developers/"],
                "temporal": "unidentified",
                "publisher": {
                    "@type": "org:Organization",
                    "name": "U.S. Census Bureau",
                    "subOrganizationOf": {
                        "@type": "org:Organization",
                        "name": "U.S. Department Of Commerce",
                        "subOrganizationOf": {
                            "@type": "org:Organization",
                            "name": "U.S. Government",
                        },
                    },
                },
            },
        ],
    },
}
