"""
This type stub file was generated by pyright.
"""

from ._monitor import TMonitor, TqdmSynchronisationWarning
from ._tqdm_pandas import tqdm_pandas
from .cli import main
from .gui import tqdm as tqdm_gui
from .gui import trange as tgrange
from .std import (
    TqdmDeprecationWarning,
    TqdmExperimentalWarning,
    TqdmKeyError,
    TqdmMonitorWarning,
    TqdmTypeError,
    TqdmWarning,
    tqdm,
    trange,
)
from .version import __version__

def tqdm_notebook(*args, **kwargs):
    """See tqdm.notebook.tqdm for full documentation"""
    ...

def tnrange(*args, **kwargs):
    """
    A shortcut for `tqdm.notebook.tqdm(xrange(*args), **kwargs)`.
    On Python3+, `range` is used instead of `xrange`.
    """
    ...
