"""
This type stub file was generated by pyright.
"""

from .std import TqdmDeprecationWarning, TqdmExperimentalWarning, TqdmKeyError, TqdmMonitorWarning, TqdmTypeError, TqdmWarning, tqdm, trange
from .gui import tqdm as tqdm_gui, trange as tgrange
from ._tqdm_pandas import tqdm_pandas
from .cli import main
from ._monitor import TMonitor, TqdmSynchronisationWarning
from .version import __version__

def tqdm_notebook(*args, **kwargs):
    """See tqdm.notebook.tqdm for full documentation"""
    ...

def tnrange(*args, **kwargs):
    """
    A shortcut for `tqdm.notebook.tqdm(xrange(*args), **kwargs)`.
    On Python3+, `range` is used instead of `xrange`.
    """
    ...

