"""
This type stub file was generated by pyright.
"""

__author__ = "github.com/casperdcl"
def tqdm_pandas(tclass, **tqdm_kwargs):
    """
    Registers the given `tqdm` instance with
    `pandas.core.groupby.DataFrameGroupBy.progress_apply`.
    """
    ...

