"""
This type stub file was generated by pyright.
"""

import sys

"""
Enables multiple commonly used features.

Method resolution order:

- `tqdm.autonotebook` without import warnings
- `tqdm.asyncio` on Python3.5+
- `tqdm.std` base class

Usage:
>>> from tqdm.auto import trange, tqdm
>>> for i in trange(10):
...     ...
"""
if sys.version_info[: 2] < (3, 5):
    tqdm = notebook_tqdm
    trange = notebook_trange
else:
    def trange(*args, **kwargs):
        """
        A shortcut for `tqdm.auto.tqdm(range(*args), **kwargs)`.
        """
        ...
    
