MOCK_API = {
    # healthcheck
    "https://api.census.gov/data/2019/acs/acs1.json": "OK",
    # groups
    "https://api.census.gov/data/2019/acs/acs1/groups.json": {
        "groups": [
            {
                "name": "B17015",
                "description": "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY FAMILY TYPE BY SOCIAL SECURITY INCOME BY SUPPLEMENTAL SECURITY INCOME (SSI) AND CASH PUBLIC ASSISTANCE INCOME",
                "variables": "https://api.census.gov/data/2019/acs/acs1/groups/B17015.json",
            },
            {
                "name": "B18104",
                "description": "SEX BY AGE BY COGNITIVE DIFFICULTY",
                "variables": "https://api.census.gov/data/2019/acs/acs1/groups/B18104.json",
            },
            {
                "name": "B18105",
                "description": "SEX BY AGE BY AMBULATORY DIFFICULTY",
                "variables": "https://api.census.gov/data/2019/acs/acs1/groups/B18105.json",
            },
        ]
    },
    # all variables
    "https://api.census.gov/data/2019/acs/acs1/variables.json": {
        "variables": {
            "B17015_001E": {
                "label": "Estimate!!Total:",
                "concept": "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY FAMILY TYPE BY SOCIAL SECURITY INCOME BY SUPPLEMENTAL SECURITY INCOME (SSI) AND CASH PUBLIC ASSISTANCE INCOME",
                "predicateType": "int",
                "group": "B17015",
                "limit": 0,
                "predicateOnly": True,
            },
            "B17015_001M": {
                "label": "Margin of Error!!Total:",
                "concept": "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY FAMILY TYPE BY SOCIAL SECURITY INCOME BY SUPPLEMENTAL SECURITY INCOME (SSI) AND CASH PUBLIC ASSISTANCE INCOME",
                "predicateType": "int",
                "group": "B17015",
                "limit": 0,
                "predicateOnly": True,
            },
            "B17015_001MA": {
                "label": "Annotation of Margin of Error!!Total:",
                "concept": "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY FAMILY TYPE BY SOCIAL SECURITY INCOME BY SUPPLEMENTAL SECURITY INCOME (SSI) AND CASH PUBLIC ASSISTANCE INCOME",
                "predicateType": "string",
                "group": "B17015",
                "limit": 0,
                "predicateOnly": True,
            },
            "B17015_001EA": {
                "label": "Annotation of Estimate!!Total:",
                "concept": "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY FAMILY TYPE BY SOCIAL SECURITY INCOME BY SUPPLEMENTAL SECURITY INCOME (SSI) AND CASH PUBLIC ASSISTANCE INCOME",
                "predicateType": "string",
                "group": "B17015",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18104_001MA": {
                "label": "Annotation of Margin of Error!!Total:",
                "concept": "SEX BY AGE BY COGNITIVE DIFFICULTY",
                "predicateType": "string",
                "group": "B18104",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18104_001EA": {
                "label": "Annotation of Estimate!!Total:",
                "concept": "SEX BY AGE BY COGNITIVE DIFFICULTY",
                "predicateType": "string",
                "group": "B18104",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18104_001M": {
                "label": "Margin of Error!!Total:",
                "concept": "SEX BY AGE BY COGNITIVE DIFFICULTY",
                "predicateType": "int",
                "group": "B18104",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18104_001E": {
                "label": "Estimate!!Total:",
                "concept": "SEX BY AGE BY COGNITIVE DIFFICULTY",
                "predicateType": "int",
                "group": "B18104",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18105_001MA": {
                "label": "Annotation of Margin of Error!!Total:",
                "concept": "SEX BY AGE BY AMBULATORY DIFFICULTY",
                "predicateType": "string",
                "group": "B18105",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18105_001EA": {
                "label": "Annotation of Estimate!!Total:",
                "concept": "SEX BY AGE BY AMBULATORY DIFFICULTY",
                "predicateType": "string",
                "group": "B18105",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18105_001E": {
                "label": "Estimate!!Total:",
                "concept": "SEX BY AGE BY AMBULATORY DIFFICULTY",
                "predicateType": "int",
                "group": "B18105",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18105_001M": {
                "label": "Margin of Error!!Total:",
                "concept": "SEX BY AGE BY AMBULATORY DIFFICULTY",
                "predicateType": "int",
                "group": "B18105",
                "limit": 0,
                "predicateOnly": True,
            },
        }
    },
    #############################
    ##### grouped variables #####
    #############################
    "https://api.census.gov/data/2019/acs/acs1/groups/B17015.json": {
        "variables": {
            "B17015_001E": {
                "label": "Estimate!!Total:",
                "concept": "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY FAMILY TYPE BY SOCIAL SECURITY INCOME BY SUPPLEMENTAL SECURITY INCOME (SSI) AND CASH PUBLIC ASSISTANCE INCOME",
                "predicateType": "int",
                "group": "B17015",
                "limit": 0,
                "predicateOnly": True,
            },
            "B17015_001M": {
                "label": "Margin of Error!!Total:",
                "concept": "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY FAMILY TYPE BY SOCIAL SECURITY INCOME BY SUPPLEMENTAL SECURITY INCOME (SSI) AND CASH PUBLIC ASSISTANCE INCOME",
                "predicateType": "int",
                "group": "B17015",
                "limit": 0,
                "predicateOnly": True,
            },
            "B17015_001MA": {
                "label": "Annotation of Margin of Error!!Total:",
                "concept": "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY FAMILY TYPE BY SOCIAL SECURITY INCOME BY SUPPLEMENTAL SECURITY INCOME (SSI) AND CASH PUBLIC ASSISTANCE INCOME",
                "predicateType": "string",
                "group": "B17015",
                "limit": 0,
                "predicateOnly": True,
            },
            "B17015_001EA": {
                "label": "Annotation of Estimate!!Total:",
                "concept": "POVERTY STATUS IN THE PAST 12 MONTHS OF FAMILIES BY FAMILY TYPE BY SOCIAL SECURITY INCOME BY SUPPLEMENTAL SECURITY INCOME (SSI) AND CASH PUBLIC ASSISTANCE INCOME",
                "predicateType": "string",
                "group": "B17015",
                "limit": 0,
                "predicateOnly": True,
            },
        }
    },
    "https://api.census.gov/data/2019/acs/acs1/groups/B18104.json": {
        "variables": {
            "B18104_001MA": {
                "label": "Annotation of Margin of Error!!Total:",
                "concept": "SEX BY AGE BY COGNITIVE DIFFICULTY",
                "predicateType": "string",
                "group": "B18104",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18104_001EA": {
                "label": "Annotation of Estimate!!Total:",
                "concept": "SEX BY AGE BY COGNITIVE DIFFICULTY",
                "predicateType": "string",
                "group": "B18104",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18104_001M": {
                "label": "Margin of Error!!Total:",
                "concept": "SEX BY AGE BY COGNITIVE DIFFICULTY",
                "predicateType": "int",
                "group": "B18104",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18104_001E": {
                "label": "Estimate!!Total:",
                "concept": "SEX BY AGE BY COGNITIVE DIFFICULTY",
                "predicateType": "int",
                "group": "B18104",
                "limit": 0,
                "predicateOnly": True,
            },
        }
    },
    "https://api.census.gov/data/2019/acs/acs1/groups/B18105.json": {
        "variables": {
            "B18105_001MA": {
                "label": "Annotation of Margin of Error!!Total:",
                "concept": "SEX BY AGE BY AMBULATORY DIFFICULTY",
                "predicateType": "string",
                "group": "B18105",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18105_001EA": {
                "label": "Annotation of Estimate!!Total:",
                "concept": "SEX BY AGE BY AMBULATORY DIFFICULTY",
                "predicateType": "string",
                "group": "B18105",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18105_001E": {
                "label": "Estimate!!Total:",
                "concept": "SEX BY AGE BY AMBULATORY DIFFICULTY",
                "predicateType": "int",
                "group": "B18105",
                "limit": 0,
                "predicateOnly": True,
            },
            "B18105_001M": {
                "label": "Margin of Error!!Total:",
                "concept": "SEX BY AGE BY AMBULATORY DIFFICULTY",
                "predicateType": "int",
                "group": "B18105",
                "limit": 0,
                "predicateOnly": True,
            },
        }
    },
    # stats
    "https://api.census.gov/data/2019/acs/acs1?get=NAME,B17015_001E,B18104_001E,B18105_001E&for=congressional%20district:*&in=state:01": [
        [
            "NAME",
            "B17015_001E",
            "B18104_001E",
            "B18105_001E",
            "state",
            "congressional district",
        ],
        [
            "Congressional District 1 (116th Congress), Alabama",
            "172441",
            "664816",
            "664816",
            "01",
            "01",
        ],
        [
            "Congressional District 3 (116th Congress), Alabama",
            "184320",
            "664930",
            "664930",
            "01",
            "03",
        ],
        [
            "Congressional District 5 (116th Congress), Alabama",
            "195668",
            "681411",
            "681411",
            "01",
            "05",
        ],
        [
            "Congressional District 4 (116th Congress), Alabama",
            "179508",
            "640347",
            "640347",
            "01",
            "04",
        ],
        [
            "Congressional District 7 (116th Congress), Alabama",
            "151225",
            "620542",
            "620542",
            "01",
            "07",
        ],
        [
            "Congressional District 2 (116th Congress), Alabama",
            "168129",
            "610312",
            "610312",
            "01",
            "02",
        ],
        [
            "Congressional District 6 (116th Congress), Alabama",
            "186592",
            "653559",
            "653559",
            "01",
            "06",
        ],
    ],
    # stats -- batched
    "https://api.census.gov/data/2019/acs/acs1?get=NAME,B17015_001E&for=congressional%20district:*&in=state:01": [
        [
            "NAME",
            "B17015_001E",
            "state",
            "congressional district",
        ],
        [
            "Congressional District 1 (116th Congress), Alabama",
            "172441",
            "01",
            "01",
        ],
        [
            "Congressional District 3 (116th Congress), Alabama",
            "184320",
            "01",
            "03",
        ],
        [
            "Congressional District 5 (116th Congress), Alabama",
            "195668",
            "01",
            "05",
        ],
        [
            "Congressional District 4 (116th Congress), Alabama",
            "179508",
            "01",
            "04",
        ],
        [
            "Congressional District 7 (116th Congress), Alabama",
            "151225",
            "01",
            "07",
        ],
        [
            "Congressional District 2 (116th Congress), Alabama",
            "168129",
            "01",
            "02",
        ],
        [
            "Congressional District 6 (116th Congress), Alabama",
            "186592",
            "01",
            "06",
        ],
    ],
    "https://api.census.gov/data/2019/acs/acs1?get=NAME,B18104_001E&for=congressional%20district:*&in=state:01": [
        [
            "NAME",
            "B18104_001E",
            "state",
            "congressional district",
        ],
        [
            "Congressional District 1 (116th Congress), Alabama",
            "664816",
            "01",
            "01",
        ],
        [
            "Congressional District 3 (116th Congress), Alabama",
            "664930",
            "01",
            "03",
        ],
        [
            "Congressional District 5 (116th Congress), Alabama",
            "681411",
            "01",
            "05",
        ],
        [
            "Congressional District 4 (116th Congress), Alabama",
            "640347",
            "01",
            "04",
        ],
        [
            "Congressional District 7 (116th Congress), Alabama",
            "620542",
            "01",
            "07",
        ],
        [
            "Congressional District 2 (116th Congress), Alabama",
            "610312",
            "01",
            "02",
        ],
        [
            "Congressional District 6 (116th Congress), Alabama",
            "653559",
            "01",
            "06",
        ],
    ],
    "https://api.census.gov/data/2019/acs/acs1?get=NAME,B18105_001E&for=congressional%20district:*&in=state:01": [
        [
            "NAME",
            "B18105_001E",
            "state",
            "congressional district",
        ],
        [
            "Congressional District 1 (116th Congress), Alabama",
            "664816",
            "01",
            "01",
        ],
        [
            "Congressional District 3 (116th Congress), Alabama",
            "664930",
            "01",
            "03",
        ],
        [
            "Congressional District 5 (116th Congress), Alabama",
            "681411",
            "01",
            "05",
        ],
        [
            "Congressional District 4 (116th Congress), Alabama",
            "640347",
            "01",
            "04",
        ],
        [
            "Congressional District 7 (116th Congress), Alabama",
            "620542",
            "01",
            "07",
        ],
        [
            "Congressional District 2 (116th Congress), Alabama",
            "610312",
            "01",
            "02",
        ],
        [
            "Congressional District 6 (116th Congress), Alabama",
            "653559",
            "01",
            "06",
        ],
    ],
    # supported geographies
    "https://api.census.gov/data/2019/acs/acs1/geography.json": {
        "default": [{"isDefault": "True"}],
        "fips": [
            {"name": "us", "geoLevelDisplay": "010", "referenceDate": "2019-01-01"},
            {"name": "region", "geoLevelDisplay": "020", "referenceDate": "2019-01-01"},
            {
                "name": "division",
                "geoLevelDisplay": "030",
                "referenceDate": "2019-01-01",
            },
            {"name": "state", "geoLevelDisplay": "040", "referenceDate": "2019-01-01"},
            {
                "name": "county",
                "geoLevelDisplay": "050",
                "referenceDate": "2019-01-01",
                "requires": ["state"],
                "wildcard": ["state"],
                "optionalWithWCFor": "state",
            },
        ],
    },
    # geography codes
    "https://api.census.gov/data/2019/acs/acs1?get=NAME&for=congressional%20district:*&in=state:01": [
        ["NAME", "state", "congressional district"],
        ["Congressional District 1 (116th Congress), Alabama", "01", "01"],
        ["Congressional District 3 (116th Congress), Alabama", "01", "03"],
        ["Congressional District 5 (116th Congress), Alabama", "01", "05"],
        ["Congressional District 4 (116th Congress), Alabama", "01", "04"],
        ["Congressional District 7 (116th Congress), Alabama", "01", "07"],
        ["Congressional District 2 (116th Congress), Alabama", "01", "02"],
        ["Congressional District 6 (116th Congress), Alabama", "01", "06"],
    ],
}
